### ISSUE TITLE
Fix uncaught error during call "Cannot read properties of undefined (reading 'outboundSeqCounter')"

### ISSUE THREAD

**Issue by bwindels** [vector-im/hydrogen-web#1012]
- when we hangup from UI, retry logic should be stopped?
 - Also, why does this appear as uncaught promise in UI
 - have stack trace:
 
```
		 		index.a4436919.js:24 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'outboundSeqCounter')
		    at Object.sendSignallingMessage (index.a4436919.js:24:22946)
		    at index.a4436919.js:24:20212
		    at Ft.run (index.a4436919.js:28:155)
		    at Ft.wrap (index.a4436919.js:27:12920)
		    at du.sendSignallingMessage (index.a4436919.js:24:20164)
		    at du.sendHangupWithCallId (index.a4436919.js:24:8415)
		    at du._hangup (index.a4436919.js:24:7363)
		    at index.a4436919.js:24:9610
```

**Comment by bwindels** [comment]
Fixed by #1016
