### ISSUE TITLE
Error when trying to login: `TypeError: Cannot read properties of undefined (reading 'identityKeys')`

### ISSUE THREAD

**Issue by MadLittleMods** [vector-im/hydrogen-web#1063]
### Reproduction instructions

 1. Latest `master` of `hydrogen-web` (07df6a88a377127f3ba253c7a5826241662eea90)
    - Versus the latest release `v0.3.8` which works fine
 1. Attempt to login, http://localhost:3000/#/login
 1. See `Something went wrong` error page

```
SessionLoadViewModel.js:81 session load error TypeError: Cannot read properties of undefined (reading 'identityKeys')
    at Session.load (http://localhost:3000/@fs/hydrogen-web/src/matrix/Session.js:499:47)
    at async Client._loadSessionInfo (http://localhost:3000/@fs/hydrogen-web/src/matrix/Client.js:285:9)
    at async Client._createSessionAfterAuth (http://localhost:3000/@fs/hydrogen-web/src/matrix/Client.js:228:13)
    at async http://localhost:3000/@fs/hydrogen-web/src/matrix/Client.js:200:13
    at async Client.startWithLogin (http://localhost:3000/@fs/hydrogen-web/src/matrix/Client.js:169:9)
```

![](https://user-images.githubusercontent.com/558581/228060996-42951093-a8aa-4eb9-84ea-529878f4ea95.png)

**Comment by bwindels** [comment]
Thanks for reporting, this was fixed in https://github.com/vector-im/hydrogen-web/commit/1c923a720bc77b8fcb4da4b1179f207dcf9be67e
