### ISSUE TITLE
Images in the timeline fail to load

### ISSUE THREAD

**Issue by bwindels** [vector-im/hydrogen-web#729]
Clicking them shows them correctly in the lightbox though.
This is on latest chromium.
This seems to happen for both unencrypted and encrypted rooms.
Unlikely but possibly related: https://github.com/vector-im/hydrogen-web/issues/687

I see these (unsure whether related) errors in the console
```
Failed to load resource: the server responded with a status of 404 ()
matrix.org/_matrix/client/r0/room_keys/keys/!SdfdNBPLectQhkggTM%3Amatrix.org/undefined?version=1&_cacheBuster=1824865657300068:1          Failed to load resource: the server responded with a status of 404 ()
sw.js:322 got a push message Object
sw.js:322 showing new message notification
10The FetchEvent for "<URL>" resulted in a network error response: the promise was rejected.
sw.js:321          Uncaught (in promise) TypeError: Failed to fetch
    at T (sw.js:321:29)
matrix.org/_matrix/client/r0/sync?since=s2899318558_757284974_10598136_1335313994_1343936335_3211033_476458750_3519014380_212414&timeout=30000&filter=5&_cacheBuster=5851402487826187:1          Failed to load resource: net::ERR_FAILED
sw.js:321          Uncaught (in promise) TypeError: Failed to fetch
    at T (sw.js:321:29)
matrix.org/_matrix/client/versions?&_cacheBuster=2689591324852046:1          Failed to load resource: net::ERR_FAILED
sw.js:321          Uncaught (in promise) TypeError: Failed to fetch
    at T (sw.js:321:29)
matrix.org/_matrix/client/versions?&_cacheBuster=7310134355093185:1          Failed to load resource: net::ERR_FAILED
sw.js:321          Uncaught (in promise) TypeError: Failed to fetch
    at T (sw.js:321:29)
matrix.org/_matrix/client/versions?&_cacheBuster=1204158109782454:1          Failed to load resource: net::ERR_FAILED
sw.js:321          Uncaught (in promise) TypeError: Failed to fetch
    at T (sw.js:321:29)
matrix.org/_matrix/client/r0/sync?since=s2899326444_757284974_10608688_1335318519_1343943009_3211043_476460774_3519045497_212414&timeout=30000&filter=5&_cacheBuster=7906250914897359:1          Failed to load resource: net::ERR_FAILED
sw.js:321          Uncaught (in promise) TypeError: Failed to fetch
    at T (sw.js:321:29)
matrix.org/_matrix/client/r0/sync?since=s2899413077_757284974_10727889_1335367324_1344010555_3211090_476483969_3519227122_212414&timeout=30000&filter=5&_cacheBuster=1835417321427368:1          Failed to load resource: net::ERR_FAILED
sw.js:321          Uncaught (in promise) TypeError: Failed to fetch
    at T (sw.js:321:29)
matrix.org/_matrix/client/versions?&_cacheBuster=8597991173233255:1          Failed to load resource: net::ERR_FAILED
sw.js:321          Uncaught (in promise) TypeError: Failed to fetch
    at T (sw.js:321:29)
matrix.org/_matrix/client/versions?&_cacheBuster=2691605056005422:1          Failed to load resource: net::ERR_FAILED
sw.js:321          Uncaught (in promise) TypeError: Failed to fetch
    at T (sw.js:321:29)
matrix.org/_matrix/client/versions?&_cacheBuster=7314194513772991:1          Failed to load resource: net::ERR_FAILED
sw.js:321          Uncaught (in promise) TypeError: Failed to fetch
    at T (sw.js:321:29)
matrix.org/_matrix/client/r0/sync?since=s2899417823_757284974_10734665_1335370143_1344014582_3211090_476485130_3519234176_212414&timeout=30000&filter=5&_cacheBuster=237562931207346:1          Failed to load resource: net::ERR_FAILED
matrix.org/_matrix/client/r0/rooms/!ewdjhNcPcEmYNKzlWp%3At2l.io/state/m.room.member/%40natem%3Aelement.io?&_cacheBuster=6694866877649369:1          Failed to load resource: the server responded with a status of 404 ()
```

**Comment by bwindels** [comment]
It says src=(unknown) for the <img> tag:
![screen](https://user-images.githubusercontent.com/274386/165946892-0642edaf-d8c7-42a7-b06b-cc8e30dae57a.png)
