### ISSUE TITLE
SDK asset build fails on Windows

### ISSUE THREAD

**Issue by MadLittleMods** [vector-im/hydrogen-web#858]
SDK asset build fails on Windows. Broke in `v0.3.0`, different error in `v0.3.1`, still broken in `v0.3.2`

Windows 10 ❌:
```
$ git checkout v0.3.0
$ yarn run vite build -c vite.sdk-assets-config.js
yarn run v1.22.18
$ C:\Users\MLM\Documents\GitHub\element\hydrogen-web\node_modules\.bin\vite build -c vite.sdk-assets-config.js
locally linked postcss
[build-themes] themeConfig.themes is not iterable
error during build:
TypeError: themeConfig.themes is not iterable
    at Object.buildStart (C:\Users\MLM\Documents\GitHub\element\hydrogen-web\vite.sdk-assets-config.js:154:46)
    at C:\Users\MLM\Documents\GitHub\vite\node_modules\.pnpm\rollup@2.62.0\node_modules\rollup\dist\shared\rollup.js:22740:25
    at async Promise.all (index 1)
    at rollupInternal (C:\Users\MLM\Documents\GitHub\vite\node_modules\.pnpm\rollup@2.62.0\node_modules\rollup\dist\shared\rollup.js:23456:9)
    at doBuild (C:\Users\MLM\Documents\GitHub\vite\packages\vite\src\node\build.ts:548:20)
    at build (C:\Users\MLM\Documents\GitHub\vite\packages\vite\src\node\build.ts:352:12)
    at CAC.<anonymous> (C:\Users\MLM\Documents\GitHub\vite\packages\vite\src\node\cli.ts:164:7)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

$ git checkout v0.3.1
$ yarn run vite build -c vite.sdk-assets-config.js
yarn run v1.22.18
$ C:\Users\MLM\Documents\GitHub\element\hydrogen-web\node_modules\.bin\vite build -c vite.sdk-assets-config.js
locally linked postcss
cleanUrl(id) C:/Users/MLM/Documents/GitHub/element/hydrogen-web/src/platform/web/ui/css/themes/element/theme.css C:/Users/MLM/Documents/GitHub/element/hydrogen-web/src/platform/web/ui/css/themes/element/theme.css?type=runtime
[build-themes] Could not load C:/Users/MLM/Documents/GitHub/element/hydrogen-web/src/platform/web/ui/css/themes/element/theme.css?variant=light: ENOENT: no such file or directory, open 'C:\Users\MLM\Documents\GitHub\element\C:\Users\MLM\Documents\GitHub\element\hydrogen-web\src\platform\web\ui\css\themes\element\theme.css'
error during build:
Error: Could not load C:/Users/MLM/Documents/GitHub/element/hydrogen-web/src/platform/web/ui/css/themes/element/theme.css?variant=light: ENOENT: no such file or directory, open 'C:\Users\MLM\Documents\GitHub\element\C:\Users\MLM\Documents\GitHub\element\hydrogen-web\src\platform\web\ui\css\themes\element\theme.css'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

$ git checkout v0.3.2
# same error
```

macOS 12.5.1 ✅:

```
$ yarn run vite build -c vite.sdk-assets-config.js
yarn run v1.22.18
$ /Users/eric/Documents/github/element/hydrogen-web/node_modules/.bin/vite build -c vite.sdk-assets-config.js
Generated an empty chunk: "index"
✨  Done in 1.36s.
```

### Dev notes

https://github.com/vector-im/hydrogen-web/compare/v0.2.33...v0.3.1

**Comment by MadLittleMods** [comment]
I think this was fixed by https://github.com/vector-im/hydrogen-web/issues/858
